excluded:
  - build

disabled_rules:
  - trailing_whitespace
  - line_length
  - file_length
  - type_body_length
  - cyclomatic_complexity
  - function_body_length
  - unused_closure_parameter
  - comma
  - colon
  - mark
  - vertical_whitespace
  - identifier_name
  - statement_position
  - trailing_comma
  - trailing_semicolon
  - closure_parameter_position 