name: DeepSleep
options:
  bundleIdPrefix: com.deepsleep.app
  deploymentTarget:
    iOS: 17.0
packages:
  FSCalendar:
    url: https://github.com/WenchaoD/FSCalendar.git
    from: 2.8.4
pods:
  - FirebaseAnalytics
  - FirebaseCrashlytics
  - Alamofire
  - KeychainAccess
targets:
  DeepSleep:
    type: application
    platform: iOS
    sources:
      - path: DeepSleepApp
        group: ""
    info:
      path: DeepSleepApp/AppInfo.plist
      properties:
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UILaunchStoryboardName: LaunchScreen
        LSApplicationQueriesSchemes:
          - "kakaokompassauth"
          - "kakaolink"
        REPLICATE_API_TOKEN: $(REPLICATE_API_TOKEN)
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
    settings:
      base:
        INFOPLIST_FILE: "DeepSleepApp/AppInfo.plist"
        DEVELOPMENT_TEAM: YOUR_TEAM_ID
        CODE_SIGN_STYLE: Automatic
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.0"
    configFiles:
      Debug: DeepSleepApp/Secrets.xcconfig
      Release: DeepSleepApp/Secrets.xcconfig
    dependencies:
      - package: FSCalendar
  DeepSleepTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
        excludes: [Info.plist]
    info:
      path: Tests/Tests-Info.plist
    dependencies:
      - target: DeepSleep