name: DeepSleep
options:
  bundleIdPrefix: com.deepsleep.app
  deploymentTarget:
    iOS: 17.0
packages:
  FSCalendar:
    url: https://github.com/WenchaoD/FSCalendar.git
    from: 2.8.4
pods:
  - FirebaseAnalytics
  - FirebaseCrashlytics
  - Alamofire
  - KeychainAccess
targets:
  DeepSleep:
    type: application
    platform: iOS
    sources:
      - path: DeepSleep
    info:
      path: DeepSleep/Info.plist
      properties:
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UILaunchStoryboardName: LaunchScreen
        LSApplicationQueriesSchemes:
          - "kakaokompassauth"
          - "kakaolink"
    settings:
      base:
        DEVELOPMENT_TEAM: YOUR_TEAM_ID
        CODE_SIGN_STYLE: Automatic
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.0"
    dependencies:
      - package: FSCalendar
  DeepSleepTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
        excludes: [Info.plist]
    info:
      path: Tests/Tests-Info.plist
    dependencies:
      - target: DeepSleep 