name: iOS CI & Coverage
on:
  push:
    branches: [ai_hybrid]
  pull_request:
    branches: [ai_hybrid]
jobs:
  build-test-coverage:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby & Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - name: Install Fastlane
        run: gem install fastlane
      - name: Xcode Select
        run: sudo xcode-select -s "/Applications/Xcode_15.0.1.app"
      - name: Run tests with coverage
        run: |
          xcodebuild test -scheme DeepSleep \
            -destination "platform=iOS Simulator,name=iPhone 15 Pro" \
            -enableCodeCoverage YES \
            -derivedDataPath DerivedData
      - name: Generate coverage report (HTML)
        run: |
          set -e
          BUNDLE=$(find DerivedData/Logs/Test -name '*.xcresult' | head -n1)
          if [[ -z "$BUNDLE" ]]; then echo "No xcresult found"; exit 1; fi
          xcrun xccov view --report --json "$BUNDLE" > coverage.json
          xcrun xccov view --report "$BUNDLE" > coverage.txt
          xcrun xccov view --html "$BUNDLE" > coverage.html || true
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            coverage.json
            coverage.txt
            coverage.html
      # (선택) gh-pages 배포 스텝 추가 가능 